# Generated by Django 4.1.1 on 2022-09-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
