# Generated by Django 4.1.1 on 2022-09-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_user_username_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
